### PR TITLE
Feature/#65 feature changer after click to feature list sometimes missing

### PR DESCRIPTION
**Pull request by dopenguin**
## Summary

- Moved `getFeaturesCluster` from `@polar/core` to the lib package `@polar/lib-get-cluster`; referred to as `getCluster` from now on
- `getCluster` has had several changes
  - Retrieves all features from the `source` instead of only the ones in the current extent
  - Added a third parameter to possibly use the functionality for differently set ids
  - throws errors if the given input does not yield the expected result
  - Add the entrance feature "on top" of others for easier usage
  - Set the layerId as a parameter on the cluster
- Created `listableLayerSources` which is now used as a base for `listFeatures`
- Renamed `actions.ts` of gfi to `actions/index.ts` in preparation for #33 
- If a feature with related features (cluster) is selected in the feature list, users can now toggle between the features with forward/backward buttons, just like when selecting clustered features in the map.
- If a feature becomes clustered / is no longer clustered when zooming out / in, the selected features are updated properly now based on the selected cluster in the map.

## Instructions for local reproduction and review

See #65 for scope of intended changes.

## Relevant tickets, issues, et cetera

Resolves: #65, Blocked by: #73

### CODE REVIEW

**Review by warm-coolguy — CHANGES_REQUESTED** [review]
While I agreed that zooming to the reclustered features makes sense in our last call, it feels weird to actually use it. This takes control away from the user – many changes in this remake have adressed such issues – and may annoy people. When using the map, I personally think it's plausible that people navigate away from a selected feature and just don't care about it anymore without actually closing it, searching for something else. Snapping back to the selection disturbs this flow.

At the same time, I understand that finding the currently selected feature in the map is a plausible user requirement. 

As a solution, I propose:

1. Removing the snapping back on zooming (=> People just browsing the map are not disturbed)
2. Adding a zoom-to button to the GFI window (=> People losing track of their selection can easily return)

Amazingly, fontawesome has [just the icon](https://fontawesome.com/icons/magnifying-glass-location?f=classic&s=solid) for this use case. Bravo.

Regarding code and functionality, I found no issues.

🏓 @dopenguin

**Comment by dopenguin** [comment]
> While I agreed that zooming to the reclustered features makes sense in our last call, it feels weird to actually use it. This takes control away from the user – many changes in this remake have adressed such issues – and may annoy people. When using the map, I personally think it's plausible that people navigate away from a selected feature and just don't care about it anymore without actually closing it, searching for something else. Snapping back to the selection disturbs this flow.
> 
> At the same time, I understand that finding the currently selected feature in the map is a plausible user requirement.
> 
> As a solution, I propose:
> 
>     1. Removing the snapping back on zooming (=> People just browsing the map are not disturbed)
> 
>     2. Adding a zoom-to button to the GFI window (=> People losing track of their selection can easily return)
> 
> 
> Amazingly, fontawesome has [just the icon](https://fontawesome.com/icons/magnifying-glass-location?f=classic&s=solid) for this use case. Bravo.
> 
> Regarding code and functionality, I found no issues.
> 
> 🏓 @dopenguin

I agree that the behaviour might feel annoying.  
However, the first part of the possible solution doesn't really seem to be implemented easy without excessive changes.  
The mapView is centered whenever the state value `selected` in `@polar/core` changes via a watcher.

Do you have a suggestion on how to differentiate the update of `selected` between from gfi list / click in the map and zooming while a feature is selected **without** adding information of `@polar/plugin-gfi` to `@polar/core` and generally large changes to this part of the implementation?

🏓 @warm-coolguy

**Comment by warm-coolguy** [comment]
> > While I agreed that zooming to the reclustered features makes sense in our last call, it feels weird to actually use it. This takes control away from the user – many changes in this remake have adressed such issues – and may annoy people. When using the map, I personally think it's plausible that people navigate away from a selected feature and just don't care about it anymore without actually closing it, searching for something else. Snapping back to the selection disturbs this flow.
> > At the same time, I understand that finding the currently selected feature in the map is a plausible user requirement.
> > As a solution, I propose:
> > ```
> > 1. Removing the snapping back on zooming (=> People just browsing the map are not disturbed)
> > 
> > 2. Adding a zoom-to button to the GFI window (=> People losing track of their selection can easily return)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Amazingly, fontawesome has [just the icon](https://fontawesome.com/icons/magnifying-glass-location?f=classic&s=solid) for this use case. Bravo.
> > Regarding code and functionality, I found no issues.
> > 🏓 @dopenguin
> 
> I agree that the behaviour might feel annoying. However, the first part of the possible solution doesn't really seem to be implemented easy without excessive changes. The mapView is centered whenever the state value `selected` in `@polar/core` changes via a watcher.
> 
> Do you have a suggestion on how to differentiate the update of `selected` between from gfi list / click in the map and zooming while a feature is selected **without** adding information of `@polar/plugin-gfi` to `@polar/core` and generally large changes to this part of the implementation?
> 
> 🏓 @warm-coolguy

Moving the `center`ing from `actions/useExtendedMasterportalapiMarkers` to the `vuex.ts` mutations (which may now need to become actions to be "allowed" to have side-effects on the map) could be a solution. This allows adding a flag to the payload (now `{ feature, centerOnFeature }`) to delegate control to API usage.

For centering, please remember that we need to center on the cluster, not the individual feature (that we may not be able to see directly). Hence, this *is* a larger change to the implementation. I can't think of an easier way to do this right now.

🏓 @dopenguin

**Comment by dopenguin** [comment]
> > > While I agreed that zooming to the reclustered features makes sense in our last call, it feels weird to actually use it. This takes control away from the user – many changes in this remake have adressed such issues – and may annoy people. When using the map, I personally think it's plausible that people navigate away from a selected feature and just don't care about it anymore without actually closing it, searching for something else. Snapping back to the selection disturbs this flow.
> > > At the same time, I understand that finding the currently selected feature in the map is a plausible user requirement.
> > > As a solution, I propose:
> > > ```
> > > 1. Removing the snapping back on zooming (=> People just browsing the map are not disturbed)
> > > 
> > > 2. Adding a zoom-to button to the GFI window (=> People losing track of their selection can easily return)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Amazingly, fontawesome has [just the icon](https://fontawesome.com/icons/magnifying-glass-location?f=classic&s=solid) for this use case. Bravo.
> > > Regarding code and functionality, I found no issues.
> > > 🏓 @dopenguin
> > 
> > 
> > I agree that the behaviour might feel annoying. However, the first part of the possible solution doesn't really seem to be implemented easy without excessive changes. The mapView is centered whenever the state value `selected` in `@polar/core` changes via a watcher.
> > Do you have a suggestion on how to differentiate the update of `selected` between from gfi list / click in the map and zooming while a feature is selected **without** adding information of `@polar/plugin-gfi` to `@polar/core` and generally large changes to this part of the implementation?
> > 🏓 @warm-coolguy
> 
> Moving the `center`ing from `actions/useExtendedMasterportalapiMarkers` to the `vuex.ts` mutations (which may now need to become actions to be "allowed" to have side-effects on the map) could be a solution. This allows adding a flag to the payload (now `{ feature, centerOnFeature }`) to delegate control to API usage.
> 
> For centering, please remember that we need to center on the cluster, not the individual feature (that we may not be able to see directly). Hence, this _is_ a larger change to the implementation. I can't think of an easier way to do this right now.
> 
> 🏓 @dopenguin

To make this work, a few more things had to be done. Please check, if you are fine with the implementation.

🏓 @warm-coolguy

**Comment by warm-coolguy** [comment]
> > > > While I agreed that zooming to the reclustered features makes sense in our last call, it feels weird to actually use it. This takes control away from the user – many changes in this remake have adressed such issues – and may annoy people. When using the map, I personally think it's plausible that people navigate away from a selected feature and just don't care about it anymore without actually closing it, searching for something else. Snapping back to the selection disturbs this flow.
> > > > At the same time, I understand that finding the currently selected feature in the map is a plausible user requirement.
> > > > As a solution, I propose:
> > > > ```
> > > > 1. Removing the snapping back on zooming (=> People just browsing the map are not disturbed)
> > > > 
> > > > 2. Adding a zoom-to button to the GFI window (=> People losing track of their selection can easily return)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Amazingly, fontawesome has [just the icon](https://fontawesome.com/icons/magnifying-glass-location?f=classic&s=solid) for this use case. Bravo.
> > > > Regarding code and functionality, I found no issues.
> > > > 🏓 @dopenguin
> > > 
> > > 
> > > I agree that the behaviour might feel annoying. However, the first part of the possible solution doesn't really seem to be implemented easy without excessive changes. The mapView is centered whenever the state value `selected` in `@polar/core` changes via a watcher.
> > > Do you have a suggestion on how to differentiate the update of `selected` between from gfi list / click in the map and zooming while a feature is selected **without** adding information of `@polar/plugin-gfi` to `@polar/core` and generally large changes to this part of the implementation?
> > > 🏓 @warm-coolguy
> > 
> > 
> > Moving the `center`ing from `actions/useExtendedMasterportalapiMarkers` to the `vuex.ts` mutations (which may now need to become actions to be "allowed" to have side-effects on the map) could be a solution. This allows adding a flag to the payload (now `{ feature, centerOnFeature }`) to delegate control to API usage.
> > For centering, please remember that we need to center on the cluster, not the individual feature (that we may not be able to see directly). Hence, this _is_ a larger change to the implementation. I can't think of an easier way to do this right now.
> > 🏓 @dopenguin
> 
> To make this work, a few more things had to be done. Please check, if you are fine with the implementation.
> 
> 🏓 @warm-coolguy

🚀 @dopenguin

**Review by warm-coolguy — APPROVED** [review]

**Pull request merged**
