### PR TITLE
refactor: simplify pins plugin

### PR DESCRIPTION
**Pull request by warm-coolguy**
## Summary

- remove redundant information in store.state
- simplify calls that only appear as pair

## Instructions for local reproduction and review

Check functionality of the Pins plugin in the usual clients.

### CODE REVIEW

**Review by dopenguin — CHANGES_REQUESTED** [review]
A changelog entry is missing, otherwise this looks good!

🏓 @warm-coolguy

**Comment by warm-coolguy** [comment]
> A changelog entry is missing, otherwise this looks good!
> 
> 🏓 @warm-coolguy

Since this is a refactor, I do not deem a changelog entry (and thus potentially a release) necessary; neither should any change in this be interesting for users as only internals have been modified.

Do you still insist? If so, what kind of note do you have in mind? Something along the lines of `Chore: Refactored parts of the data handling`?

🏓 @dopenguin

**Comment by dopenguin** [comment]
> > A changelog entry is missing, otherwise this looks good!
> > 🏓 @warm-coolguy
> 
> Since this is a refactor, I do not deem a changelog entry (and thus potentially a release) necessary; neither should any change in this be interesting for users as only internals have been modified.
> 
> Do you still insist? If so, what kind of note do you have in mind? Something along the lines of `Chore: Refactored parts of the data handling`?
> 
> 🏓 @dopenguin

I think it is valid to include refactoring as part of the Changelog. `Chore: Refactor parts of the data handling` seems fitting

🏓 @warm-coolguy

**Comment by warm-coolguy** [comment]
> > > A changelog entry is missing, otherwise this looks good!
> > > 🏓 @warm-coolguy
> > 
> > 
> > Since this is a refactor, I do not deem a changelog entry (and thus potentially a release) necessary; neither should any change in this be interesting for users as only internals have been modified.
> > Do you still insist? If so, what kind of note do you have in mind? Something along the lines of `Chore: Refactored parts of the data handling`?
> > 🏓 @dopenguin
> 
> I think it is valid to include refactoring as part of the Changelog. `Chore: Refactor parts of the data handling` seems fitting
> 
> 🏓 @warm-coolguy

https://github.com/Dataport/polar/pull/130/commits/d98ec1c97623581aac42d6055e07186d39ccf549

🏓 @dopenguin

**Review by dopenguin — APPROVED** [review]
🚀 @warm-coolguy

**Pull request merged**
