### PR TITLE
Slightly enlarge markers for easier usage on mobile devices

### PR DESCRIPTION
**Pull request by dopenguin**
## Summary

Slightly enlarge markers for easier usage on mobile devices.

## Instructions for local reproduction and review

Run meldemichel and check if it is large enough (but not too large).

### CODE REVIEW

**Review by warm-coolguy — CHANGES_REQUESTED** [review]
🏓 @dopenguin Merge conflict.

While we're at it:

- I fiddled with the `clusterDistance` in `enableClustering`. 30 seems too low and has lots of overlaps. I tried 50 and it looks *somewhat* right, but also makes some areas look emptier than they are. What is your opinion on a good value for this?
- Do you think it makes sense to make marker size configurable? Since it's related to `clusterDistance`, it might make sense to be able to fiddle with both on a per-client basis. Especially since a map with a very low marker count may find use in comically large markers to make sparse contents easier to find.

**Comment by dopenguin** [comment]
> 🏓 @dopenguin Merge conflict.
> 
> While we're at it:
> 
>     * I fiddled with the `clusterDistance` in `enableClustering`. 30 seems too low and has lots of overlaps. I tried 50 and it looks _somewhat_ right, but also makes some areas look emptier than they are. What is your opinion on a good value for this?
> 
>     * Do you think it makes sense to make marker size configurable? Since it's related to `clusterDistance`, it might make sense to be able to fiddle with both on a per-client basis. Especially since a map with a very low marker count may find use in comically large markers to make sparse contents easier to find.

- It seems like `40` seems large enough and the areas don't really seem empty. Do we wanna roll with that?
- I think it makes complete sense to add that as a possibility! I'll get going on that!

**Comment by warm-coolguy** [comment]
> > 🏓 @dopenguin Merge conflict.
> > While we're at it:
> > ```
> > * I fiddled with the `clusterDistance` in `enableClustering`. 30 seems too low and has lots of overlaps. I tried 50 and it looks _somewhat_ right, but also makes some areas look emptier than they are. What is your opinion on a good value for this?
> > 
> > * Do you think it makes sense to make marker size configurable? Since it's related to `clusterDistance`, it might make sense to be able to fiddle with both on a per-client basis. Especially since a map with a very low marker count may find use in comically large markers to make sparse contents easier to find.
> > ```
> 
>     * It seems like `40` seems large enough and the areas don't really seem empty. Do we wanna roll with that?
> 
>     * I think it makes complete sense to add that as a possibility! I'll get going on that!
> 
> 
> **Edit**: The parameter `layerConf` does not have a type, as it is based on the [services.json](https://bitbucket.org/geowerkstatt-hamburg/masterportal/src/dev/doc/services.json.md). However, I can't seem to find any information regarding the `clusterDistance` in that documentation. Is it a parameter we added for POLAR? Also, where would you put the parameters for the clusterMarker size?

`40` seems fine.

To my knowledge, `clusterDistance` is only documented in the masterportalAPI's JSDoc. I don't remember when or why it was added.

> Also, where would you put the parameters for the clusterMarker size?

First idea that comes to mind is as a direct child to `extendedMasterportalapiMarkers`.

**Comment by dopenguin** [comment]
> > > 🏓 @dopenguin Merge conflict.
> > > While we're at it:
> > > ```
> > > * I fiddled with the `clusterDistance` in `enableClustering`. 30 seems too low and has lots of overlaps. I tried 50 and it looks _somewhat_ right, but also makes some areas look emptier than they are. What is your opinion on a good value for this?
> > > 
> > > * Do you think it makes sense to make marker size configurable? Since it's related to `clusterDistance`, it might make sense to be able to fiddle with both on a per-client basis. Especially since a map with a very low marker count may find use in comically large markers to make sparse contents easier to find.
> > > ```
> > 
> > 
> > ```
> > * It seems like `40` seems large enough and the areas don't really seem empty. Do we wanna roll with that?
> > 
> > * I think it makes complete sense to add that as a possibility! I'll get going on that!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Edit**: The parameter `layerConf` does not have a type, as it is based on the [services.json](https://bitbucket.org/geowerkstatt-hamburg/masterportal/src/dev/doc/services.json.md). However, I can't seem to find any information regarding the `clusterDistance` in that documentation. Is it a parameter we added for POLAR? Also, where would you put the parameters for the clusterMarker size?
> 
> `40` seems fine.
> 
> To my knowledge, `clusterDistance` is only documented in the masterportalAPI's JSDoc. I don't remember when or why it was added.
> 
> > Also, where would you put the parameters for the clusterMarker size?
> 
> First idea that comes to mind is as a direct child to `extendedMasterportalapiMarkers`.

Adjusted size `clusterDistance` (12b01377) and made the marker size configurable (dd95be25).

🏓 @warm-coolguy

**Comment by warm-coolguy** [comment]
> > > > 🏓 @dopenguin Merge conflict.
> > > > While we're at it:
> > > > ```
> > > > * I fiddled with the `clusterDistance` in `enableClustering`. 30 seems too low and has lots of overlaps. I tried 50 and it looks _somewhat_ right, but also makes some areas look emptier than they are. What is your opinion on a good value for this?
> > > > 
> > > > * Do you think it makes sense to make marker size configurable? Since it's related to `clusterDistance`, it might make sense to be able to fiddle with both on a per-client basis. Especially since a map with a very low marker count may find use in comically large markers to make sparse contents easier to find.
> > > > ```
> > > 
> > > 
> > > ```
> > > * It seems like `40` seems large enough and the areas don't really seem empty. Do we wanna roll with that?
> > > 
> > > * I think it makes complete sense to add that as a possibility! I'll get going on that!
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Edit**: The parameter `layerConf` does not have a type, as it is based on the [services.json](https://bitbucket.org/geowerkstatt-hamburg/masterportal/src/dev/doc/services.json.md). However, I can't seem to find any information regarding the `clusterDistance` in that documentation. Is it a parameter we added for POLAR? Also, where would you put the parameters for the clusterMarker size?
> > 
> > 
> > `40` seems fine.
> > To my knowledge, `clusterDistance` is only documented in the masterportalAPI's JSDoc. I don't remember when or why it was added.
> > > Also, where would you put the parameters for the clusterMarker size?
> > 
> > 
> > First idea that comes to mind is as a direct child to `extendedMasterportalapiMarkers`.
> 
> Adjusted size `clusterDistance` ([12b0137](https://github.com/Dataport/polar/commit/12b01377bd0a5443066113d42ea7dd7ae1bd77a6)) and made the marker size configurable ([dd95be2](https://github.com/Dataport/polar/commit/dd95be25228b03203b39f19d90a9aa8d784f036d)).
> 
> 🏓 @warm-coolguy

🚀 @dopenguin

**Review by warm-coolguy — APPROVED** [review]

**Pull request merged**
