### PR TITLE
Change all asides to divs as they hold main content

### PR DESCRIPTION
**Pull request by dopenguin**
## Summary

Change all `<aside>`-elements to `<div>`-elements with the same style as prior `<aside>`-elements, as the main content is currently displayed in those elements.  
Adjusted the box-shadow on hover to be more visible.

## Instructions for local reproduction and review

`npm run pages:build` & `npm run pages:build:serve`

### CODE REVIEW

**Review by warm-coolguy — CHANGES_REQUESTED** [review]
The various nested plugin examples have not been changed from `aside` to `div`. Is this intentional?

🏓 @dopenguin

**Comment by dopenguin** [comment]
> The various nested plugin examples have not been changed from `aside` to `div`. Is this intentional?
> 
> 🏓 @dopenguin

This was an oversight as I only changed the main file. Will change it as well for the other files.

**Comment by dopenguin** [comment]
> > The various nested plugin examples have not been changed from `aside` to `div`. Is this intentional?
> > 🏓 @dopenguin
> 
> This was an oversight as I only changed the main file. Will change it as well for the other files.

Done 05304510b7faf0a309bb3d48829a219af3759395

🏓 @warm-coolguy

**Review by warm-coolguy — APPROVED** [review]
🚀 @dopenguin

**Pull request merged**
